#!/usr/bin/env python3
"""Push the generated WeChat HTML article to draft box."""

import json, os, re, sys, ssl, urllib.request, urllib.error

APPID = "wx10db5c92106d9a30"
APPSECRET = "b1042249e1c1f9a32fd7c46650811c93"
HTML_FILE = os.path.join(os.path.dirname(os.path.dirname(os.path.abspath(__file__))),
                         "docs", "articles", "GB28181国标推流实战分析-deepblue.html")
ARTICLES_DIR = os.path.join(os.path.dirname(os.path.dirname(os.path.abspath(__file__))),
                             "docs", "articles")
IMAGES = [
    r"C:\Users\lhx\AppData\Roaming\Typora\typora-user-images\image-20260803174033564.png",
    r"C:\Users\lhx\AppData\Roaming\Typora\typora-user-images\image-20260803173605727.png",
    # Mermaid diagrams (generated by gen_gb28181_wechat.py)
    os.path.join(ARTICLES_DIR, "mermaid_diagram_1.png"),
    os.path.join(ARTICLES_DIR, "mermaid_diagram_2.png"),
]
ACCESS_TOKEN = os.environ.get("WX_TOKEN", "")

def api(path, data=None, files=None):
    ctx = ssl.create_default_context()
    url = f"https://api.weixin.qq.com{path}"
    if files:
        boundary = "----WebKitFormBoundary7MA4YWxkTrZu0gW"
        body = b""
        for name, (filename, content, ct) in files.items():
            body += f"--{boundary}\r\n".encode()
            body += f'Content-Disposition: form-data; name="{name}"; filename="{filename}"\r\n'.encode()
            body += f"Content-Type: {ct}\r\n\r\n".encode()
            body += content + b"\r\n"
        body += f"--{boundary}--\r\n".encode()
        req = urllib.request.Request(url, data=body)
        req.add_header("Content-Type", f"multipart/form-data; boundary={boundary}")
    elif data:
        req = urllib.request.Request(url, data=json.dumps(data, ensure_ascii=False).encode("utf-8"))
        req.add_header("Content-Type", "application/json; charset=utf-8")
    else:
        req = urllib.request.Request(url)
    try:
        with urllib.request.urlopen(req, timeout=30, context=ctx) as resp:
            return json.loads(resp.read().decode("utf-8"))
    except urllib.error.HTTPError as e:
        return json.loads(e.read().decode("utf-8"))

def get_token():
    r = api(f"/cgi-bin/token?grant_type=client_credential&appid={APPID}&secret={APPSECRET}")
    if "access_token" in r:
        return r["access_token"]
    print(f"Token error: {r}")
    sys.exit(1)

def upload_img(token, path):
    with open(path, "rb") as f:
        content = f.read()
    fn = os.path.basename(path)
    ext = fn.rsplit(".",1)[-1].lower()
    mime = {"jpg":"image/jpeg","jpeg":"image/jpeg","png":"image/png","gif":"image/gif"}.get(ext,"image/png")
    r = api(f"/cgi-bin/media/uploadimg?access_token={token}", files={"media":(fn, content, mime)})
    return r.get("url")

def upload_cover(token, path):
    with open(path, "rb") as f:
        content = f.read()
    fn = os.path.basename(path)
    ext = fn.rsplit(".",1)[-1].lower()
    mime = {"jpg":"image/jpeg","jpeg":"image/jpeg","png":"image/png"}.get(ext,"image/png")
    r = api(f"/cgi-bin/material/add_material?access_token={token}&type=image", files={"media":(fn, content, mime)})
    return r.get("media_id")

def main():
    print("=" * 50)
    print("Push WeChat HTML to Draft Box")
    print("=" * 50)

    # 1. Token
    print("\n[1/4] Access token...")
    token = get_token()
    print(f"      OK: {token[:20]}...")

    # 1.5 Define metadata
    title = "干货｜逐帧剖析 GB28181 推流：信令协商与媒体传输全解"
    digest = "基于实际网络抓包，逐帧分析GB28181国标推流的完整SIP信令交互，涵盖注册、保活、SDP协商、RTP over TCP媒体流传输与BYE会话拆除全流程。"

    # 2. Upload images & replace in HTML
    print("\n[2/4] Upload images & replace URLs...")
    with open(HTML_FILE, "r", encoding="utf-8") as f:
        html = f.read()

    # Replace H1 + title in HTML to match
    html = html.replace(
        ">逐帧剖析 GB28181 推流：信令协商与媒体传输全解<",
        f">{title}<"
    )
    html = html.replace(
        "<title>逐帧剖析 GB28181 推流：信令协商与媒体传输全解</title>",
        f"<title>{title}</title>"
    )

    for img_path in IMAGES:
        if not os.path.exists(img_path):
            print(f"      SKIP (not found): {img_path}")
            continue
        print(f"      Upload: {os.path.basename(img_path)} ({os.path.getsize(img_path)/1024:.1f}KB)...")
        wx_url = upload_img(token, img_path)
        if wx_url:
            # Replace both slash styles
            for p in [img_path, img_path.replace("\\", "/")]:
                html = html.replace(p, wx_url)
            print(f"      -> {wx_url[:60]}...")
        else:
            print(f"      FAILED")

    # check no local paths remain
    remaining = re.findall(r'src="[A-Z]:\\[^"]+\.(png|jpg|jpeg|gif)"', html, re.I)
    if remaining:
        print(f"      WARN: {len(remaining)} local image path(s) still in HTML")

    # 3. Cover image
    print("\n[3/4] Cover image...")
    cover_id = upload_cover(token, IMAGES[1])
    print(f"      media_id: {cover_id}" if cover_id else f"      FAILED")

    # 4. Draft
    print("\n[4/4] Push draft...")

    article = {
        "title": title,
        "author": "damon.liu",
        "digest": digest,
        "content": html,
        "content_source_url": "",
        "need_open_comment": 0,
        "only_fans_can_comment": 0,
    }
    if cover_id:
        article["thumb_media_id"] = cover_id

    r = api(f"/cgi-bin/draft/add?access_token={token}", data={"articles": [article]})

    if "media_id" in r:
        print(f"      SUCCESS! media_id: {r['media_id']}")
        print(f"\nDone. Visit mp.weixin.qq.com -> Drafts.")
    else:
        errcode = r.get("errcode", "?")
        errmsg = r.get("errmsg", "unknown")
        hints = {40001:"token expired",40007:"bad media_id",45009:"rate limit",53010:"bad format"}
        print(f"      FAILED: {errcode} - {errmsg} {hints.get(errcode,'')}")

if __name__ == "__main__":
    main()
